### ISSUE TITLE
Turn Project into Org

### ISSUE THREAD

**Issue by Moikapy** [rotten-soup/Rotten-Soup#50]
Would it be possible to turn this project into an organization so that it's easier for people to help?

**Comment by Larkenx** [comment]
That's definitely a possibility! I will think about this some more. Haven't had anyone express interest in contributing to the project before 🥇

**Comment by Moikapy** [comment]
Well I'll take a look around things to see how i can help, I tried out the game and thought it was fun.

**Comment by Larkenx** [comment]
created this organization and transferred the Rotten Soup repo https://github.com/rotten-soup
