### ISSUE TITLE
Converting Project to Electron App?

### ISSUE THREAD

**Issue by Moikapy** [rotten-soup/Rotten-Soup#51]
Instead of connecting to a webserver/link, would it possible to convert the game into an electron app to be played locally as a desktop app.

**Comment by Larkenx** [comment]
Yep, it is possible - I have done it in the past. The issue is just that maintains both a web based version of the game and electron version of the game is tricky

**Comment by Moikapy** [comment]
Well if we make this an Org it may be easier for development.
What we do is create the core game as a repo and then use it as a module in a seperate repo for the electron version so that when we launch the electron app it starts the game. This way the game itself can be updated and (hopefully) the same version for the desktop app.

**Comment by Moikapy** [comment]
So all we would need to do is (brief todo):
- [ ] Create Rotton-Soup-Desktop Repo. 
- [ ] Clone Rotton-Soup into Repo as a module.
- [ ] Set up Electron to run the Rotton-Soup Game.

**Comment by Larkenx** [comment]
org creation is done; sent @Moikapy an invite. feel free to create a separate electron release repo, with this project as a module

**Comment by Moikapy** [comment]
Would you be able to send again? I don't think I received the invite

**Comment by Moikapy** [comment]
Invite Complete

**Comment by Carl-Bowen** [comment]
Hey. Would love to contribute, please send me an invite also :)
